version: "2"

services:
  sonarqube:
    image: sonarqube:8.2-community
    depends_on:
      - db
    expose:
      - 9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: _3_^PDwWQb^JeqzD
      VIRTUAL_HOST: 'sonarqube.conkelhomelab.net'
      LETSENCRYPT_HOST: 'sonarqube.conkelhomelab.net'
      LETSENCRYPT_EMAIL: 'josh@conkel.net'

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
  db:
    image: postgres
    ports:
      - 5432
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: _3_^PDwWQb^JeqzD
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

networks:
    default:
        external:
            name: nginx-proxy

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data:
