services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: gitlab-ce
    hostname: 'gitlab-temp.conkelhomelab.net'
    env_file:
      - ./.env
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-temp.conkelhomelab.net'
        gitlab_rails['initial_shared_runners_registration_token'] = "YVk2J5GRL58zkPWX"
        gitlab_rails['initial_root_password'] = "SlalomTraining99!"
        nginx['listen_port'] = 8010
      VIRTUAL_HOST: 'gitlab-temp.conkelhomelab.net'
      VIRTUAL_PORT: 8010
      LETSENCRYPT_HOST: 'gitlab-temp.conkelhomelab.net'
      LETSENCRYPT_EMAIL: 'josh@conkel.net'
    expose:
      - 8010
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    hostname: 'runner.conkelhomelab.net'
    container_name: runner
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - '$RUNNER_HOME/config/gitlab-runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-runner

  workstation:
    image: 'dorowu/ubuntu-desktop-lxde-vnc'
    container_name: workstation
    hostname: 'workstation.conkelhomelab.net'
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: 'workstation.conkelhomelab.net'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'workstation.conkelhomelab.net'
      LETSENCRYPT_EMAIL: 'josh@conkel.net'
      HTTP_PASSWORD: 'SlalomTraining99!'
      VNC_PASSWORD: 'SlalomTraining99!'
    expose:
      - 80
    volumes:
      - '/dev/shm:/dev/shm'

  django.Nv:
    image: 'hysnsec/django.nv:latest'
    container_name: django.nv
    restart: unless-stopped
    container_name: djangonv
    hostname: 'django-nv.conkelhomelab.net'
    expose:
      - 8000
    environment:
        VIRTUAL_HOST: 'django-nv.conkelhomelab.net'
        LETSENCRYPT_HOST: 'django-nv.conkelhomelab.net'
        LETSENCRYPT_EMAIL: 'josh@conkel.net'

networks:
    default:
        external:
            name: nginx-proxy
    gitlab-runner:
        external:
            name: gitlab-runner
